### ISSUE TITLE
Media Keys

### ISSUE THREAD

**Issue by garyee** [healzer/BandcampPlayer#1]
Hi,
really love your implementation of the bandcamp player. I wanted to know if you could maybe implement Media Keys.
The latest browsers support the playback control with the use of the special media keys on some keyboards, headphones or other devices. This would be very nice to have.

**Comment by healzer** [comment]
Thanks for suggesting this, I also had the idea for quite some time, it is especially useful for mobile phones. The media keys have been added, enjoy! <3 :)

**Comment by garyee** [comment]
Man that was very fast! Thank you!!!!!

**Comment by healzer** [comment]
Anytime my man
